### ISSUE TITLE
Cannot resolve com.silamoney:SilamoneySDK:0.2.9-rc

### ISSUE THREAD

**Issue by chrisbra-riftpay** [Sila-Money/sila-sdk-java#12]
Trying to use sila in a fresh spring boot project, I saw a similar issue but it doesn't seem to help in our case.
![Screenshot from 2020-07-14 23-03-16](https://user-images.githubusercontent.com/58540465/87498629-41031780-c626-11ea-9f0c-b2fcdfad3402.png)

```xml
	<properties>
		<java.version>11</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
	</properties>
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>11</source>
					<target>11</target>
				</configuration>
			</plugin>
```

**Comment by chepix10** [comment]
Hi @chrisbra-riftpay 
Thanks for reaching out to us. We published the v0.2.9-rc version today. Also, there was a type in the README
Can you try again with this configuration?
https://github.com/Sila-Money/sila-sdk-java#installation

**Comment by chrisbra-riftpay** [comment]
> Hi @chrisbra-riftpay
> Thanks for reaching out to us. We published the v0.2.9-rc version today. Also, there was a typo in the README
> Can you try again with this configuration?
> https://github.com/Sila-Money/sila-sdk-java#installation

We tried last night and this morning to no resolve. When we revert to an older version (0.2.7-rc) it works but we want to use the current master version.

**Comment by chrisbra-riftpay** [comment]
![Screenshot from 2020-07-15 19-27-44](https://user-images.githubusercontent.com/58540465/87609721-4e291080-c6d1-11ea-8be8-717f212f3ccc.png)

**Comment by chepix10** [comment]
https://search.maven.org/artifact/com.silamoney.client/SilamoneySDK
v0.2.9-rc is listed on the maven repository. Can you try again?
![image](https://user-images.githubusercontent.com/11563946/87609956-3184dc80-c6c1-11ea-9a4c-a6d23100be5c.png)
